// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WMS.Modules.Transfer.Infrastructure.Persistence;

#nullable disable

namespace WMS.Modules.Transfer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransferDbContext))]
    partial class TransferDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transfer")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WMS.Modules.Transfer.Domain.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DestinationWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_warehouse_id");

                    b.Property<DateTimeOffset?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<DateTimeOffset?>("ShippedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shipped_at_utc");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_warehouse_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_stock_transfers");

                    b.ToTable("stock_transfers", "transfer");
                });

            modelBuilder.Entity("WMS.Modules.Transfer.Domain.StockTransferLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("StockTransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_transfer_lines");

                    b.HasIndex("StockTransferId")
                        .HasDatabaseName("ix_stock_transfer_lines_stock_transfer_id");

                    b.ToTable("stock_transfer_lines", "transfer");
                });

            modelBuilder.Entity("WMS.Modules.Transfer.Domain.StockTransferLine", b =>
                {
                    b.HasOne("WMS.Modules.Transfer.Domain.StockTransfer", null)
                        .WithMany("Lines")
                        .HasForeignKey("StockTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transfer_lines_stock_transfers_stock_transfer_id");
                });

            modelBuilder.Entity("WMS.Modules.Transfer.Domain.StockTransfer", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
